spring.application.name=cderc-backend

#spring.datasource.url=jdbc:postgresql://localhost:5432/cderc_db
spring.datasource.url=${DATABASE_URL}

spring.datasource.username=cderc_user
spring.datasource.password=cderc_password

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

server.port=${PORT:8080}